name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - master  # ✅ make sure this matches your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full Git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ✅ Full history needed to push to GitLab

      - name: Push mirror to GitLab
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab ${{ secrets.GITLAB_REPO }}
          git push --mirror gitlab
