name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone GitHub repo as mirror
        run: |
          git clone --mirror https://github.com/${{ github.repository }} repo
          cd repo
          git remote add gitlab ${{ secrets.GITLAB_REPO }}
          git push --mirror gitlab
