name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history from GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # <== This is the key fix!

      - name: Mirror to GitLab
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab ${{ secrets.GITLAB_REPO }}
          git push --mirror gitlab
