name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add GitLab remote and push mirror
        env:
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
        run: |
          git remote add gitlab $GITLAB_REPO
          git push --mirror gitlab
