name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - master  # or 'main' based on your repo

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full Git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to GitLab (branches + tags only)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab ${{ secrets.GITLAB_REPO }}
          git push --prune gitlab "+refs/heads/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
